VERSION=unknown

ifdef DEVICE
# Device build
STAGING_DIR=/srv/preware/build/staging/armv7
ifeq ($(shell uname -s),Darwin)
CC=/opt/PalmPDK/arm-gcc/bin/arm-none-linux-gnueabi-gcc
else
CC=/srv/preware/build/toolchain/cs07q3armel/build/arm-2007q3/bin/arm-none-linux-gnueabi-gcc
endif
else
# Emulator build
STAGING_DIR=/srv/preware/build/staging/i686
CC=/srv/preware/build/toolchain/i686-unknown-linux-gnu/build/i686-unknown-linux-gnu/bin/i686-unknown-linux-gnu-gcc
endif

CPPFLAGS := -g -DVERSION=\"${VERSION}\" -I${STAGING_DIR}/usr/include/glib-2.0 -I${STAGING_DIR}/usr/lib/glib-2.0/include -I${STAGING_DIR}/usr/include
LDFLAGS  := -g -L${STAGING_DIR}/usr/lib -llunaservice -lmjson -lglib-2.0 -lpthread

saverestore: saverestore.o luna_service.o luna_methods.o

install: saverestore
#	- ssh root@webos killall org.webosinternals.saverestore
#	scp saverestore root@webos:/var/usr/sbin/org.webosinternals.saverestore.new
#	ssh root@webos mv /var/usr/sbin/org.webosinternals.saverestore.new /var/usr/sbin/org.webosinternals.saverestore
	novacom put file://home/root/saverestore < saverestore

clobber:
	rm -rf *.o saverestore
